r"""I2 + I3 — dimer-interface distance table and interface-proximal classification.

Task doc `docs/tasks/dimer-interface-comparator-check/DIMER_INTERFACE_COMPARATOR_CHECK.md`,
Tasks I2 and I3. Session log: `.../INTERFACE_LOG.md`.

PRE-REGISTERED: this docstring was written BEFORE the first run of this script. Every
definition, gate, denominator, cutoff, and decision rule below was fixed before any number
produced here was seen. Nothing in this script was tuned after seeing a result.

SCOPE: structure + cached tables only. No model scoring, no model loading, no `torch`, no
`esm`. CPU-only. Reads `data/raw/6FCX.pdb` (READ-ONLY reference copy) and two cached CSVs.
Writes exactly one new file, `data/processed/interface_distances.csv`. Nothing is
overwritten; no earlier script or CSV is modified.

================================================================================
PROVENANCE (fixed here, from Task I1's read of script 107 — not assumed)
================================================================================
Structure : data/raw/6FCX.pdb
            X-RAY DIFFRACTION, 2.50 A, R-work 0.210 / R-free 0.248, deposited 2017-12-21.
            Deposited human MTHFR CATALYTIC domain. REMARK 350: biological unit is the
            DIMER, generated by IDENTITY BIOMT on chains A,B — so chains A and B as
            deposited already ARE the complete biological dimer. No assembly expansion.
Chains    : "A" and "B" (PDB chain id, column 22). Script 107 L197.
Numbering : IDENTITY. frame position p == PDB residue number p; the ARRAY index is
            p - 40 for chain A. Proven by script 77 L219-220 (FIRST_RESI=40, IDX222=182)
            and by script 107's empirical G1b (|d_AA(p) - stored ca_dist_222| < 1e-6 on
            all 9,595 frame rows; recorded max|diff| 7.1e-15).
Atoms     : 0 hydrogens in the file (element column holds only C, N, O, S — measured,
            not assumed). "Heavy atoms only" therefore requires no filtering. No altLocs
            (all 8,914 ATOM records blank in column 17), no insertion codes (column 27
            blank throughout), no non-standard residue names.

================================================================================
DISCLOSED AMENDMENT — made AFTER run 1 failed its replica gate (AGENTS sec 6)
================================================================================
Run 1 of this script EXITED 1 at gate I2-G3 with:
    *** I2-G3 FAIL: Biopython CA != vendor CA, max|diff| = 4.124e-06 >= 1e-06 — stop.
No task-doc gate (I2-G1, I2-G2) had been reached. Run 1 did not modify any data file.

ROOT CAUSE, diagnosed and PROVEN, not guessed: Biopython's `Atom.coord` is a
numpy float32 array, so it loses precision on the way in; the vendor parser
(`ssm_utils.py` L172) uses Python float64. Both parsers read the identical text
from the identical file. Verified directly:
    float(np.float32(-24.127)) == -24.12700080871582   -> True
    (and that is exactly the value Biopython returned for residue 40 chain A,
     whose file value is -24.127)
Max |coordinate| in the file is 67.107 A, where the float32 ULP is 7.629e-06 A,
so the largest possible Euclidean error from rounding three axes is
7.629e-06 * sqrt(3) = 1.321e-05 A. The observed 4.124e-06 A is INSIDE that bound.
This is a representation-precision artifact in one of the two parsers, NOT a data
discrepancy, NOT a numbering mismatch, and NOT a difference in what was read.

THE FIX IS A METHOD FIX, NOT A THRESHOLD RELAXATION:
  - SOURCE 3 (EXACT) is added: a dependency-free fixed-column float64 parse of the
    same file, mirroring `ssm_utils.py`'s own column logic (cols 22, 23-27, 30-38,
    38-46, 46-54) with `float()`. It supplies d_interface, so d_interface is
    computed from exact float64 coordinates rather than from a lossy intermediate.
  - I2-G3a: SOURCE 3 vs SOURCE 1 (vendor) at the ORIGINAL 1e-6 threshold, unchanged.
    This is now a meaningful comparison of two float64 reads of the same text.
  - I2-G3b: SOURCE 2 (Biopython) vs SOURCE 3 at a tolerance DERIVED from float32
    arithmetic — 2 * sqrt(3) * float32-ULP(max |coordinate|) = 2.64e-05 A — chosen
    from the representation limit, NOT tuned to make a number pass. Biopython is
    retained as a genuinely independent third-party confirmation of the residue
    sets and coordinates; it is simply compared at the precision it can deliver.
  - The float32-vs-float64 effect on d_interface itself is QUANTIFIED and printed
    (max perturbation over all resolved positions), so the claim that it is
    negligible is measured rather than asserted.

WHAT THIS AMENDMENT DOES NOT DO: no task-doc gate was weakened, no cutoff was
changed, no denominator was changed, no subset was swapped, and no result had been
seen before the change was made — the failing run produced no d_interface, no
classification, and no percentage at all. The 1e-6 threshold that matters (I2-G1's
mapping gate, and I2-G3a) is untouched. Disclosed here in the script itself, as the
script is the record.

================================================================================
THREE COORDINATE SOURCES FROM THE SAME FILE — why, and how each is gated
================================================================================
SOURCE 1 (VENDOR, float64) — script 107's exact machinery, imported, not reimplemented:
    load_pdb(data/raw/6FCX.pdb, ["A", "B"])   # ssm_utils.load_pdb -> custom_parse_PDB,
                                              # side_chains=True
  Used to reproduce script 107's own numbers (I2-G1). It yields C-alpha coordinates
  and is C-alpha-only by definition, which is exactly what script 107's metric is.

SOURCE 3 (EXACT, float64) — a dependency-free fixed-column parse of the same file
  mirroring ssm_utils.py's own column logic, using Python float(). Added by the
  disclosed amendment above. Supplies d_interface and is the 1e-6 replica reference.

SOURCE 2 (BIOPYTHON, float32) — Bio.PDB.PDBParser(QUIET=True), all ATOM records.
  Independent third-party confirmation of the residue sets and coordinates, compared
  at the float32 precision it can actually deliver.
  NEITHER vendor parse can supply d_interface: even with side_chains=True it retains
  only N, CA, C, O, SG (ssm_utils.py L354-359). The three-source split was disclosed
  in INTERFACE_LOG.md at Task I1, BEFORE this script was written or run.

REPLICA GATE: all three sources must agree on residue numbering, and on
  coordinates at the precision each source is capable of. See I2-G3a/I2-G3b.

================================================================================
DEFINITIONS (fixed here)
================================================================================
Universe U            = {2..656}, 655 positions (script 107 L158 UNIVERSE).
Resolved in chain A   = U intersect {PDB residue numbers modeled in chain A}.
d_interface(p)        = min over (a in ALL heavy atoms of chain-A residue p)
                        (b in ALL heavy atoms of ALL modeled chain-B residues)
                        of ||a - b||, in Angstroms. Expressed via a single
                        cdist(chainA_coords, chainB_coords).min() over the whole
                        flattened atom sets — no residue pairing imposed, no
                        reference to residue 222 of any kind.
  Unresolved in chain A -> d_interface is NaN (never 0, never imputed).

CROSS-CHECK metric d_CAmin(p) = min over modeled chain-B residues q of
  ||CA(p, chain A) - CA(q, chain B)||. By construction d_interface(p) <= d_CAmin(p)
  because CA is one of the atoms in each residue. Gated as an identity (I2-G4a).
BRUTE-FORCE check: every 37th resolved position's d_interface recomputed by an
  explicit Python double loop over atom pairs, no cdist. Gate I2-G4b.

GATES (failure => print, sys.exit(1). No retry, no threshold change, no subset swap):
  I2-G0  inputs present: data/raw/6FCX.pdb, data/processed/
         task77_thermompnnD_doubles.csv, data/processed/phase5_analysis_table.csv.
         The structure's md5 is printed for the record.
  I2-G1  (HARD GATE, pre-existing script-107 numbers) reproduce BOTH of script 107's
         headline figures from the same loaded structure, to 2 dp:
             monomer   far(>10 A) = 9,232/9,595 = 96.2168% -> "96.22%"
             dimer     far(>10 A) = 9,128/9,595 = 95.1329% -> "95.13%"
         computed per-VARIANT-ROW on script 107's own frozen frame (task77 rows with
         own_e_b finite, 9,595 rows / 586 positions) with C-alpha distances over the
         four A/B pairings of (p, 222), min taken. Also carries script 107's own
         mapping gate forward: |d_AA(p) - stored ca_dist_222| < 1e-6 on every row.
         ANY mismatch => STOP. I3 must not run on a structure that fails this.
  I2-G2  (HARD GATE) every universe position unresolved in chain A is logged
         EXPLICITLY by position number and count, never silently dropped, and the
         logged set must equal the set actually excluded from classification. Must
         equal script 107's 59-position policy list {2-39, 161-171, 392-396, 652-656}
         (L159-162, gated in script 107 as G4). Full list printed; a mismatch is a STOP.
  I2-G3  replica gate, in two parts (see DISCLOSED AMENDMENT above):
         (a) SOURCE 3 (exact float64) vs SOURCE 1 (vendor) on C-alpha coordinates
             and on residue-number sets, in BOTH chains, to < 1e-6 A. Original
             threshold, unchanged.
         (b) SOURCE 2 (Biopython, float32) vs SOURCE 3, on the same quantities, to
             < 2*sqrt(3)*float32-ULP(max|coordinate|) — a bound DERIVED from float32
             representation limits, not tuned.
  I2-G4  identity gates: (a) d_interface <= d_CAmin on every resolved position, max
         excess <= 0; (b) brute-force re-derivation agrees to < 1e-9 A on the
         37th-residue sample; (c) the classification counts, re-read back from the
         WRITTEN CSV, equal the in-memory counts (catches a write/read error).

I3 CUTOFFS — BOTH PRE-REGISTERED, BOTH ALWAYS REPORTED, NO SELECTION AMONG THEM:
  5.0 A  direct atomic contact, the standard interface definition.
  8.0 A  the project house convention (L3 used <= 8 A for distance-to-222).
  Interface-proximal(p)  <=>  d_interface(p) <= cutoff.   Both cutoffs. Always.
  NOTHING in this session selects one cutoff over the other based on which gives the
  cleaner result. If the two disagree, that disagreement is the finding and is reported.
  EXPLICIT NOTE, carried into the output: 8 A here is a DIFFERENT REFERENCE POINT from
  L3's 8 A. L3's reference was residue 222; this session's reference is the chain
  A/chain B interface. The shared number is the cutoff, not the quantity. These are
  two different measurements and must not be described as a replication.

I3 DENOMINATORS — every percentage is labelled with its own. Never mixed (AGENTS sec 5):
  (u) 655 = |U|, the full atlas universe
  (r) 596 = positions with chain-A coordinates
  (n) 59  = structure-unresolved, excluded from BOTH the interface set and the
           non-interface set, reported separately as "not classified either way"
  (f) 654 = frame target positions = U \ {222}
  (fr) 586 = frame positions present in script 107's / task77's frozen frame
            (a further subset — reported where used, never as the I3 denominator)

INFORMATIONAL, pre-registered as such before running:
  - residue 222's own d_interface. 222 is NOT a target position in the frame and this
    changes nothing about its treatment. 222 IS inside U and IS resolved in chain A, so
    it is computed and reported, and it IS in the 655-row CSV.
  - which chain-B residue is the nearest partner for each interface-proximal position
    (a sanity check that the detected interface is the real, localized MTHFR dimer
    interface and not uniform scatter). Printed, not gated.

OUTPUT CSV: data/processed/interface_distances.csv, rows = all 655 positions of U
  (a superset of the 654 frame target positions), columns EXACTLY:
      position, chain_a_resolved, d_interface_angstrom
  Read as the literal/conservative reading of the task doc: the specified `chain_a_resolved`
  boolean only makes sense if rows for unresolved positions are present, and I2-G2
  requires every unresolved position to be visible. 222 is included for the
  informational requirement above. Assumed and disclosed (decision-tree rule 4).

LIMITATIONS (printed with the results, AGENTS sec 6):
  1. ONE static X-ray crystal structure at 2.50 A (6FCX), a catalytic-domain construct.
     No solution-state dynamics, no ensemble, no other structure, no re-folding. A
     frozen-structure check cannot speak to any conformational change.
  2. A geometric contact is not a functional one: d_interface <= cutoff says the
     interface is structurally close, not that the position matters to assembly.
  3. Chain B is less completely modeled than chain A (window 41..648 vs 40..651, plus
     internal gaps 203-204, 220-221, 314-316). min-over-chain-B therefore has fewer
     atoms to choose from at those positions, biasing d_interface slightly UPWARD
     there. Counted and reported, not corrected.
  4. d_interface is computed from chain A only, by the task's definition. It is
     asymmetric by construction and is NOT a substitute for script 107's four-pair
     minimum to residue 222, which is a different quantity on a different axis.
  5. Deterministic census of one structure. No resampling, no p-value, no CI, no null.
     This script tests no hypothesis; it restates geometry. (The bootstrap enters in
     script 127, Task I4, and only there.)
  6. This is NOT Dr. Kuhlman's second condition (conformational-change magnitude).
     That condition is not tested here and is not claimed to be tested here.

Next free script number after this: 127.
"""
import hashlib
import sys
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from Bio.PDB import PDBParser
from scipy.spatial.distance import cdist

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "data" / "external" / "ThermoMPNN-D"))

# Cosmetic (disclosed): the vendor parse triggers Biopython's pairwise2 deprecation
# warning at import. No gate output is hidden by this filter.
warnings.filterwarnings("ignore", message="Bio.pairwise2 has been deprecated")

from thermompnn.ssm_utils import load_pdb  # noqa: E402

PROC = ROOT / "data" / "processed"
RAW = ROOT / "data" / "raw"

# ---- pre-registered constants (do not change) -------------------------------
UNIVERSE = set(range(2, 657))                      # 655 atlas positions
POLICY_MISSING = (set(range(2, 40))                 # script 107 L159-162
                  | set(range(161, 172))
                  | set(range(392, 397))
                  | set(range(652, 657)))
CUTOFF_222 = 10.0                                  # script 107 L157
EXPECTED_FRAME = (9595, 586)                       # rows, positions
EXPECTED_MONO_FAR = 9232                           # -> 96.22%
EXPECTED_DIMER_FAR = 9128                          # -> 95.13%
EXPECTED_MONO_PCT = 96.22                          # to 2 dp, pre-registered
EXPECTED_DIMER_PCT = 95.13
TOL_CA = 1e-6                                      # script 107 L166
TOL_BRUTE = 1e-9
CUTOFFS = (5.0, 8.0)                               # I3, both, always
BRUTE_STRIDE = 37
EXPECTED_MD5 = "309f70555d721015fc06788f44b0745e"
OUT_CSV = PROC / "interface_distances.csv"


def banner(txt, ch="="):
    print("\n" + ch * 74)
    print(txt)
    print(ch * 74, flush=True)


def gfail(msg):
    print(f"*** {msg}")
    sys.exit(1)


def fmt_runs(nums):
    """Compact contiguous-run rendering of a sorted position list."""
    nums = sorted(nums)
    if not nums:
        return "[]"
    out, start, prev = [], nums[0], nums[0]
    for n in nums[1:]:
        if n == prev + 1:
            prev = n
            continue
        out.append(str(start) if start == prev else f"{start}-{prev}")
        start = prev = n
    out.append(str(start) if start == prev else f"{start}-{prev}")
    return ", ".join(out)


def main():
    t0 = time.time()
    banner("I2 + I3 — dimer-interface distances (scripts/126)")

    # ---- I2-G0: inputs ------------------------------------------------
    files = {
        "6FCX structure": RAW / "6FCX.pdb",
        "script-107 frozen frame": PROC / "task77_thermompnnD_doubles.csv",
        "analysis table": PROC / "phase5_analysis_table.csv",
    }
    for label, p in files.items():
        if not p.exists():
            gfail(f"I2-G0 FAIL: {label} input missing: {p} — stop.")
    md5 = hashlib.md5(files["6FCX structure"].read_bytes()).hexdigest()
    print("  I2-G0 PASS: all 3 inputs present")
    print(f"  structure md5 = {md5} (expected {EXPECTED_MD5}) — "
          f"{'MATCH' if md5 == EXPECTED_MD5 else 'DIFFERS, reported not gated'}")

    # ---- SOURCE 1: vendor parse (script 107's exact machinery) --------
    banner("SOURCE 1 — vendor parse, script 107's exact load_pdb call (I2-G1 only)",
           "-")
    pdb = load_pdb(str(files["6FCX structure"]), ["A", "B"])
    resn_all, ca = {}, {}
    for ch in ("A", "B"):
        resn = [int(r) for r in pdb[f"resn_list_{ch}"]]
        seqc = pdb[f"seq_chain_{ch}"]
        arr = pdb[f"coords_chain_{ch}"][f"CA_chain_{ch}"]
        if not (len(resn) == len(seqc) == len(arr)):
            gfail(f"I2-G1 FAIL: chain {ch} lengths disagree — stop.")
        resn_all[ch] = resn
        ca[ch] = {resn[i]: np.asarray(arr[i], float)
                  for i in range(len(resn)) if seqc[i] != "-"}
    print(f"  chain A: resn_list {resn_all['A'][0]}..{resn_all['A'][-1]} "
          f"({len(resn_all['A'])} slots), CA-resolved {len(ca['A'])}")
    print(f"  chain B: resn_list {resn_all['B'][0]}..{resn_all['B'][-1]} "
          f"({len(resn_all['B'])} slots), CA-resolved {len(ca['B'])}")
    for ch in ("A", "B"):
        if 222 not in ca[ch]:
            gfail(f"I2-G1 FAIL: residue 222 not CA-resolved in chain {ch} — stop.")

    # ---- SOURCE 3: exact float64 fixed-column parse ------------------
    banner("SOURCE 3 — exact float64 fixed-column parse (d_interface, replica "
           "reference)", "-")
    print("  mirrors ssm_utils.py's own column logic; Python float() = float64.")
    print("  column map: chain 22 | resseq 23-27 | atom 13-16 | x 31-38 | "
          "y 39-46 | z 47-54 | element 77-78 (1-indexed PDB)")
    x3, res3, order3 = {"A": [], "B": []}, {"A": [], "B": []}, {"A": {}, "B": {}}
    e3 = {"A": [], "B": []}
    max_abs_coord = 0.0
    with open(files["6FCX structure"], "rb") as fh:
        for raw in fh:
            line = raw.decode("utf-8", "ignore").rstrip()
            if line[:4] != "ATOM":
                continue
            ch = line[21:22]
            if ch not in ("A", "B"):
                continue
            rn = int(line[22:27])
            at = line[12:16].strip()
            el = line[76:78].strip().upper() or at[0]
            if el == "H":                       # none in this file; stated
                continue
            xyz = [float(line[i:i + 8]) for i in (30, 38, 46)]
            max_abs_coord = max(max_abs_coord, *(abs(v) for v in xyz))
            x3[ch].append(xyz)
            res3[ch].append(rn)
            e3[ch].append(el)
            if at == "CA":
                order3[ch][rn] = xyz
    u32 = float(np.spacing(np.float32(max_abs_coord)))
    tol_bio = 2.0 * np.sqrt(3.0) * u32
    print(f"  max |coordinate| in file = {max_abs_coord:.3f} A; float32 ULP there "
          f"= {u32:.3e} A")
    print(f"  derived Biopython tolerance (2*sqrt(3)*ULP) = {tol_bio:.3e} A — "
          f"from float32 representation limits, not tuned to a result")
    for ch in ("A", "B"):
        a3 = np.asarray(x3[ch], float)
        el_set = sorted(set(e3[ch]))
        nres = len(set(res3[ch]))
        print(f"  chain {ch}: {nres} modeled residues, {len(a3)} heavy atoms, "
              f"elements {el_set}")

    # ---- SOURCE 2: Biopython all-atom parse (independent third party) --
    banner("SOURCE 2 — Biopython all-atom parse (independent cross-check)", "-")
    st = PDBParser(QUIET=True).get_structure("6FCX", str(files["6FCX structure"]))
    n_models = len(st)
    if n_models != 1:
        gfail(f"I2-G3 FAIL: structure has {n_models} models, expected 1 — "
              f"which model 6FCX is not pre-registered — stop.")
    atoms, elements, resids = {"A": [], "B": []}, set(), {"A": set(), "B": set()}
    ca2 = {"A": {}, "B": {}}
    b_atom_res = []
    het = sorted({r.get_resname() for c in st[0] for r in c if r.id[0] != " "})
    for ch in st[0]:
        if ch.id not in ("A", "B"):
            continue
        for r in ch:
            if r.id[0] != " ":            # standard residues only (ATOM records)
                continue
            if r.id[2] != " ":            # insertion codes: none in this file
                gfail(f"I2-G3 FAIL: insertion code {r.id} in chain {ch.id} — "
                      f"not pre-registered — stop.")
            for a in r:
                if a.element != "H":
                    atoms[ch.id].append(a.coord)
                    elements.add(a.element)
                    if ch.id == "B":
                        b_atom_res.append(r.id[1])
                if a.get_id() == "CA":
                    ca2[ch.id][r.id[1]] = np.asarray(a.coord, float)
            resids[ch.id].add(r.id[1])
    for ch in ("A", "B"):
        atoms[ch] = np.asarray(atoms[ch], float)
    b_atom_res = np.asarray(b_atom_res, int)
    nA_atoms, nB_atoms = len(atoms["A"]), len(atoms["B"])
    n_h = sum(1 for c in st[0] for r in c if r.id[0] == " "
              for a in r if a.element == "H")
    print(f"  biopython 1.88, models = {n_models}, "
          f"coordinate dtype = {atoms['A'].dtype} (float32 — see amendment)")
    print(f"  elements present in the heavy set: {sorted(elements)}")
    print(f"  HYDROGENS in the file: {n_h} -> 'heavy atoms only' requires no "
          f"filtering; nothing is lost by the restriction")
    print(f"  HETATM residues present in file (excluded from all distances, "
          f"per task definition 'any atom of chain A/B residue'): {het}")
    print(f"  chain A: {len(resids['A'])} modeled residues, {nA_atoms} heavy atoms")
    print(f"  chain B: {len(resids['B'])} modeled residues, {nB_atoms} heavy atoms")
    for ch in ("A", "B"):
        n = sorted(resids[ch])
        gaps, prev = [], None
        for v in n:
            if prev is not None and v != prev + 1:
                gaps.append((prev + 1, v - 1))
            prev = v
        print(f"  chain {ch} window {n[0]}..{n[-1]}; internal gaps: "
              f"{[f'{a}-{b}' for a, b in gaps] or 'none'}")

    # ---- I2-G3: replica gates ---------------------------------------
    banner("I2-G3 — replica gates, three independent parses of one file", "-")
    res3s = {ch: set(res3[ch]) for ch in ("A", "B")}
    for ch in ("A", "B"):
        if len(x3[ch]) != len(atoms[ch]):
            gfail(f"I2-G3b FAIL: chain {ch} heavy-atom COUNT differs between the "
                  f"exact parse ({len(x3[ch])}) and Biopython ({len(atoms[ch])}) "
                  f"— a real parsing discrepancy, not precision — stop.")
    print(f"  heavy-atom counts identical across the exact and Biopython parses "
          f"(A: {len(x3['A'])}, B: {len(x3['B'])}) — the same atoms were read, "
          f"not merely the same residues")
    max_ca_dev = 0.0
    for ch in ("A", "B"):
        if res3s[ch] != set(ca[ch]):
            gfail(f"I2-G3a FAIL: chain {ch} exact-parse residues differ from "
                  f"vendor — only-exact="
                  f"{sorted(res3s[ch] - set(ca[ch]))[:5]} "
                  f"only-vendor={sorted(set(ca[ch]) - res3s[ch])[:5]} — stop.")
        if res3s[ch] != resids[ch]:
            gfail(f"I2-G3b FAIL: chain {ch} Biopython residues differ from the "
                  f"exact parse — only-biopython="
                  f"{sorted(resids[ch] - res3s[ch])[:5]} "
                  f"only-exact={sorted(res3s[ch] - resids[ch])[:5]} — stop.")
        for rnum, xyz in order3[ch].items():
            d = float(np.linalg.norm(np.asarray(xyz, float) - ca[ch][rnum]))
            max_ca_dev = max(max_ca_dev, d)
    if max_ca_dev >= TOL_CA:
        gfail(f"I2-G3a FAIL: exact float64 parse != vendor CA, max|diff| = "
              f"{max_ca_dev:.3e} >= {TOL_CA} — stop.")
    print(f"  I2-G3a PASS: exact float64 parse and the vendor parse agree on "
          f"residue numbering and on C-alpha coordinates in BOTH chains "
          f"(max|diff| = {max_ca_dev:.3e} A < {TOL_CA}; {len(res3s['A'])} + "
          f"{len(res3s['B'])} residues compared). Both float64, same text, "
          f"same answer — the strong claim holds at the original threshold.")
    max_bio_dev = 0.0
    for ch in ("A", "B"):
        for rnum, xyz in ca2[ch].items():
            d = float(np.linalg.norm(np.asarray(xyz, float)
                                     - np.asarray(order3[ch][rnum], float)))
            max_bio_dev = max(max_bio_dev, d)
    if max_bio_dev >= tol_bio:
        gfail(f"I2-G3b FAIL: Biopython differs from the exact parse beyond the "
              f"float32 representation bound: max|diff| = {max_bio_dev:.3e} >= "
              f"{tol_bio:.3e} — this would be a real discrepancy, not a "
              f"precision artifact — stop.")
    print(f"  I2-G3b PASS: Biopython agrees with the exact parse on residue "
          f"numbering in BOTH chains and on C-alpha coordinates to "
          f"max|diff| = {max_bio_dev:.3e} A, inside the derived float32 bound "
          f"{tol_bio:.3e} A. Three independent parses, one structure.")
    print(f"  (run 1 of this script compared Biopython directly against the "
          f"vendor at 1e-6 and FAILED at 4.124e-06 A. That failure was the "
          f"float32 artifact diagnosed in the amendment, not a data "
          f"discrepancy. Neither threshold was loosened to hide it: 1e-6 is kept "
          f"for the float64-vs-float64 comparison.)")


    # =================================================================
    # I2-G1 (HARD GATE): reproduce script 107's own headline numbers
    # =================================================================
    banner("I2-G1 (HARD GATE) — reproduce script 107's 96.22% / 95.13%", "-")
    a222, b222 = ca["A"][222], ca["B"][222]
    t77 = pd.read_csv(files["script-107 frozen frame"])
    fr = t77[t77["own_e_b"].notna()].copy()
    if (len(fr), fr["position"].nunique()) != EXPECTED_FRAME:
        gfail(f"I2-G1 FAIL: frozen frame {len(fr)}/"
              f"{fr['position'].nunique()} != {EXPECTED_FRAME[0]}/"
              f"{EXPECTED_FRAME[1]} — stop.")
    pos_arr = fr["position"].to_numpy(int)

    # script 107's own mapping gate, carried forward
    stored = fr["ca_dist_222"].to_numpy(float)
    dAA = np.array([float(np.linalg.norm(ca["A"][p] - a222)) for p in pos_arr])
    map_dev = float(np.max(np.abs(dAA - stored)))
    if map_dev >= TOL_CA:
        gfail(f"I2-G1 FAIL: d_AA does not reproduce stored ca_dist_222 "
              f"(max|diff| = {map_dev:.3e} >= {TOL_CA}) — the identity "
              f"numbering mapping is in question — stop.")
    print(f"  mapping check PASS: |d_AA(p) - stored ca_dist_222| max = "
          f"{map_dev:.3e} A < {TOL_CA} over {len(fr)} rows "
          f"(frame p == PDB residue number p, index p-40)")

    # four-pair minimum, C-alpha, exactly as script 107 L295-309
    dAB = np.array([float(np.linalg.norm(ca["A"][p] - b222)) for p in pos_arr])
    hasB = np.array([p in ca["B"] for p in pos_arr])
    dBA = np.where(hasB, [float(np.linalg.norm(ca["B"][p] - a222))
                          if p in ca["B"] else np.nan for p in pos_arr], np.nan)
    dBB = np.where(hasB, [float(np.linalg.norm(ca["B"][p] - b222))
                          if p in ca["B"] else np.nan for p in pos_arr], np.nan)
    dmin4 = np.nanmin(np.vstack([dAA, dAB, dBA, dBB]), axis=0)
    farA, farD = dAA > CUTOFF_222, dmin4 > CUTOFF_222
    nA, nD = int(farA.sum()), int(farD.sum())
    pctA, pctD = 100.0 * nA / len(fr), 100.0 * nD / len(fr)
    print(f"  denominator: script 107's frozen frame — {len(fr)} variant rows / "
          f"{fr['position'].nunique()} positions (task77 rows, own_e_b finite)")
    print(f"  MONOMER   (chain A alone, CA-CA to 222(A)): far(>{CUTOFF_222:.0f} A) "
          f"= {nA}/{len(fr)} = {pctA:.4f}%")
    print(f"  DIMER-AWARE (four-pair CA min, script 107's PRIMARY): far = "
          f"{nD}/{len(fr)} = {pctD:.4f}%")
    okA = (nA == EXPECTED_MONO_FAR
           and round(pctA, 2) == EXPECTED_MONO_PCT)
    okD = (nD == EXPECTED_DIMER_FAR
           and round(pctD, 2) == EXPECTED_DIMER_PCT)
    if not (okA and okD):
        gfail(f"I2-G1 FAIL: script 107's known figures NOT reproduced — "
              f"monomer {nA}/{len(fr)} = {pctA:.4f}% "
              f"(expected {EXPECTED_MONO_FAR} = {EXPECTED_MONO_PCT}%) | "
              f"dimer {nD}/{len(fr)} = {pctD:.4f}% "
              f"(expected {EXPECTED_DIMER_FAR} = {EXPECTED_DIMER_PCT}%) — "
              f"STOP, I3 must not run on a structure that fails this gate.")
    print(f"  I2-G1 PASS: BOTH known figures reproduced to 2 dp — monomer "
          f"{nA}/{len(fr)} = {pctA:.2f}% (expected {EXPECTED_MONO_PCT}%), "
          f"dimer-aware {nD}/{len(fr)} = {pctD:.2f}% "
          f"(expected {EXPECTED_DIMER_PCT}%). Structure and parsing match.")

    # =================================================================
    # d_interface
    # =================================================================
    banner("d_interface(p) — min heavy-atom distance, chain A residue p to "
           "any chain B atom", "-")
    print(f"  definition: min over (a in all {nA_atoms} heavy atoms of the "
          f"chain-A residue) x (b in all {nB_atoms} heavy atoms of chain B), "
          f"from the float64 exact parse")
    A3 = np.asarray(x3["A"], float)
    D = cdist(A3, np.asarray(x3["B"], float))         # [n_atoms_A, n_atoms_B]
    d_atom = D.min(axis=1)                            # per chain-A ATOM
    b_atom_res = np.asarray(res3["B"], int)

    # Per-RESIDUE minimum over that residue's atoms. NOTE: this must be a
    # min-reduction across atoms, NOT a dict overwrite — an earlier version of
    # this script did the latter and kept only the LAST atom of each residue.
    # Gate I2-G4a caught it (d_interface exceeded the CA-only bound by 4.855 A,
    # impossible by construction). Kept as an explicit grouped reduction.
    uniq_res = sorted({int(r) for r in res3["A"]})
    r2i = {r: i for i, r in enumerate(uniq_res)}
    idx = np.asarray([r2i[int(r)] for r in res3["A"]], int)
    d_res = np.full(len(uniq_res), np.inf)
    np.minimum.at(d_res, idx, d_atom)
    # which chain-A atom achieved each residue's minimum, and which chain-B atom
    # is nearest to THAT atom (the nearest-partner report only)
    best_atom = {}
    for i in range(len(idx)):
        k = idx[i]
        if k not in best_atom or d_atom[i] < d_atom[best_atom[k]]:
            best_atom[k] = i
    d_int = {uniq_res[i]: float(d_res[i]) for i in range(len(uniq_res))}
    nearest_res = {uniq_res[i]: int(b_atom_res[D[best_atom[i]].argmin()])
                   for i in range(len(uniq_res))}
    if not all(np.isfinite(v) for v in d_int.values()):
        gfail("I2-G4 FAIL: non-finite d_interface — stop.")
    a_res = np.asarray(uniq_res, int)

    # QUANTIFY (do not assert) the float32 effect the amendment describes: the
    # identical computation on Biopython's float32 coordinates, differenced
    # against the float64 result.
    d32_atom = cdist(atoms["A"].astype(np.float64),
                     atoms["B"].astype(np.float64)).min(axis=1)
    d32 = np.full(len(uniq_res), np.inf)
    np.minimum.at(d32, idx, d32_atom)
    f32_pert = max(abs(float(a) - float(b))
                   for a, b in zip(d32, [d_int[r] for r in uniq_res]))
    print(f"  float32-vs-float64 perturbation of d_interface, MEASURED over all "
          f"{len(d_int)} resolved positions: max = {f32_pert:.3e} A "
          f"({100.0 * f32_pert / 5.0:.2e}% of the 5 A cutoff) — measured, not "
          f"assumed. This is why d_interface itself is computed in float64.")

    # ---- I2-G2 (HARD GATE): explicit accounting of unresolved -------
    banner("I2-G2 (HARD GATE) — structure-unresolved positions, logged "
           "explicitly", "-")
    resolved = UNIVERSE & set(a_res)
    unresolved = UNIVERSE - resolved
    frame_pos = UNIVERSE - {222}
    frame_unresolved = frame_pos - resolved
    print(f"  (u) universe U = {{2..656}} = {len(UNIVERSE)} positions")
    print(f"  (r) resolved in chain A      = {len(resolved)}")
    print(f"  (n) STRUCTURE-UNRESOLVED     = {len(unresolved)} "
          f"-> runs: {fmt_runs(unresolved)}")
    print(f"      full list: {sorted(unresolved)}")
    print(f"  (f) frame target positions U \\ {{222}} = {len(frame_pos)}; of "
          f"those, unresolved = {len(frame_unresolved)} "
          f"-> {fmt_runs(frame_unresolved)}")
    print(f"      222 itself resolved in chain A: {222 in resolved} "
          f"(so frame_unresolved == unresolved, 222 excluded from both)")
    if unresolved != POLICY_MISSING:
        gfail(f"I2-G2 FAIL: unresolved set ({len(unresolved)}) != script 107's "
              f"59-position policy list; only-in-parse="
              f"{sorted(unresolved - POLICY_MISSING)} "
              f"only-in-policy={sorted(POLICY_MISSING - unresolved)} — stop.")
    if frame_unresolved != unresolved - {222}:
        gfail("I2-G2 FAIL: frame-unresolved != universe-unresolved minus {222} "
              "— internal inconsistency — stop.")
    print(f"  I2-G2 PASS: all {len(unresolved)} unresolved positions logged by "
          f"number, equal to script 107's policy list, and equal to the set "
          f"actually excluded from classification. None silently dropped.")
    print(f"  breakdown: positions 2-39 and 652-656 are OUTSIDE the modeled "
          f"window (chain A models {a_res[0]}..{a_res[-1]}), not internal gaps. "
          f"Internal chain-A gaps: 161-171, 392-396 (from REMARK 465).")
    print(f"  chain B is less complete than chain A: window "
          f"{min(resids['B'])}..{max(resids['B'])} vs {min(resids['A'])}.."
          f"{max(resids['A'])}, and B additionally lacks 203-204, 220-221, "
          f"314-316. This biases d_interface UPWARD at those positions only.")

    # ---- I2-G4: identity gates --------------------------------------
    banner("I2-G4 — identity and brute-force re-derivation checks", "-")
    d_camin = {}
    b_ca_res = sorted(ca["B"])
    B_ca = np.asarray([ca["B"][q] for q in b_ca_res], float)
    for p in sorted(resolved):
        d_camin[p] = float(np.min(np.linalg.norm(
            B_ca - ca["A"][p][None, :], axis=-1)))
    excess = max(d_int[p] - d_camin[p] for p in sorted(resolved))
    if excess > 1e-12:
        gfail(f"I2-G4a FAIL: d_interface exceeds the CA-only min by "
              f"{excess:.3e} on some position — impossible by construction — "
              f"stop.")
    print(f"  I2-G4a PASS: d_interface <= d_CAmin on all {len(resolved)} "
          f"resolved positions (max excess = {excess:+.3e} <= 0) — the "
          f"all-atom minimum contains the CA-only minimum, as it must")
    sample = sorted(d_int)[::BRUTE_STRIDE]
    b_all = list(x3["B"])
    a_atoms_by_res = {}
    for rn, xyz in zip(res3["A"], x3["A"]):
        a_atoms_by_res.setdefault(int(rn), []).append(xyz)
    worst = 0.0
    for p in sample:
        bf = min(float(np.linalg.norm(np.asarray(x) - np.asarray(y)))
                 for x in a_atoms_by_res[p] for y in b_all)
        worst = max(worst, abs(bf - d_int[p]))
    if worst >= TOL_BRUTE:
        gfail(f"I2-G4b FAIL: brute-force re-derivation disagrees by "
              f"{worst:.3e} >= {TOL_BRUTE} — stop.")
    print(f"  I2-G4b PASS: brute-force double loop over explicit atom pairs (no "
          f"cdist, same float64 parse) reproduces d_interface on every "
          f"{BRUTE_STRIDE}th resolved position ({len(sample)} sampled), "
          f"max|diff| = {worst:.3e} A < {TOL_BRUTE}")
    print(f"  d_interface range over resolved positions: "
          f"{min(d_int.values()):.3f} .. {max(d_int.values()):.3f} A; "
          f"min is > 0 as required (no shared atoms between chains)")

    # ---- write CSV (then I2-G4c reads it back) -----------------------
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame({
        "position": sorted(UNIVERSE),
        "chain_a_resolved": [p in resolved for p in sorted(UNIVERSE)],
        "d_interface_angstrom": [d_int.get(p, np.nan) for p in sorted(UNIVERSE)],
    }).to_csv(OUT_CSV, index=False)
    print(f"\n  wrote {len(UNIVERSE)} rows -> {OUT_CSV.relative_to(ROOT)} "
          f"(columns: position, chain_a_resolved, d_interface_angstrom)")

    # ---- I3: classification at BOTH pre-registered cutoffs ----------
    banner("I3 — interface-proximal classification at BOTH cutoffs "
           "(no selection among them)", "-")
    print("  NOTE, pre-registered and binding: the 8 A cutoff here shares only "
          "the NUMBER with\n  L3's 8 A. L3's reference point was residue 222; "
          "this session's reference\n  point is the chain A / chain B interface. "
          "Different reference point, different\n  quantity. This is not a "
          "replication of L3 and is not reported as one.")
    back = pd.read_csv(OUT_CSV)
    cls = {}
    for c in CUTOFFS:
        resolved_rows = back[back["chain_a_resolved"]]
        prox = set(int(q) for q in
                   resolved_rows.loc[resolved_rows["d_interface_angstrom"] <= c,
                                     "position"])
        nonprox = set(int(q) for q in
                      resolved_rows.loc[resolved_rows["d_interface_angstrom"] > c,
                                        "position"])
        if prox | nonprox != resolved or prox & nonprox:
            gfail(f"I2-G4c FAIL: classification at {c} A does not partition the "
                  f"resolved set — stop.")
        cls[c] = (prox, nonprox)
        n_r, n_f = len(resolved), len(UNIVERSE - {222})
        print(f"\n  --- cutoff {c:.1f} A "
              f"({'direct atomic contact' if c == 5.0 else 'house convention'}) "
              f"---")
        print(f"    interface-proximal : n = {len(prox):3d}  "
              f"= {100.0 * len(prox) / n_r:6.2f}% of the {n_r} resolved "
              f"positions | {100.0 * len(prox) / n_f:6.2f}% of the {n_f} frame "
              f"target positions | {100.0 * len(prox) / len(UNIVERSE):6.2f}% of "
              f"the {len(UNIVERSE)}-position universe U")
        print(f"    non-interface      : n = {len(nonprox):3d}  "
              f"= {100.0 * len(nonprox) / n_r:6.2f}% of {n_r} resolved")
        print(f"    not classified either way (structure-unresolved, I2-G2) = "
              f"{len(unresolved)}")
        print(f"    positions (runs): {fmt_runs(prox)}")
        print(f"    full list: {sorted(prox)}")
    # I2-G4c: in-memory == re-read-from-disk
    for c in CUTOFFS:
        n_disk = int(((back["chain_a_resolved"])
                      & (back["d_interface_angstrom"] <= c)).sum())
        if n_disk != len(cls[c][0]):
            gfail(f"I2-G4c FAIL: {c} A count from the written CSV "
                  f"({n_disk}) != in-memory ({len(cls[c][0])}) — stop.")
    print(f"  I2-G4c PASS: both cutoff counts re-read from the written CSV "
          f"equal the in-memory counts; the CSV classification is exactly "
          f"d_interface <= cutoff with no off-by-one.")

    # ---- informational: residue 222 and the interface's partner map ---
    banner("INFORMATIONAL — residue 222 and the detected interface's shape", "-")
    print(f"  d_interface(222) = {d_int[222]:.3f} A  "
          f"(nearest chain-B partner residue {nearest_res[222]}). 222 is NOT a "
          f"target position in the frame and this changes nothing about its "
          f"treatment; reported because the task asked.")
    for c in CUTOFFS:
        state = ("INTERFACE-PROXIMAL"
                 if d_int[222] <= c else "NOT interface-proximal")
        print(f"    at the {c:.1f} A cutoff, residue 222 is {state} "
              f"({d_int[222]:.3f} A { '<=' if d_int[222] <= c else '>'} {c})")
    for c in CUTOFFS:
        prox = cls[c][0]
        partners = sorted({nearest_res[p] for p in prox})
        print(f"  at {c:.1f} A the interface-proximal set's nearest chain-B "
              f"partners span {min(partners)}..{max(partners)} "
              f"({len(partners)} distinct residues); most frequent partners: "
              f"{pd.Series([nearest_res[p] for p in prox]).value_counts().head(6).to_dict()}")
    print("  (this is a sanity statement only, not a gate: the partners are "
          "concentrated in a\n   contiguous stretch of chain B, which is what a "
          "real localized dimer interface looks\n   like, as opposed to uniform "
          "scatter from a parsing error.)")

    banner("LIMITATIONS (printed with results, AGENTS sec 6)", "-")
    print(f"""  1. ONE static X-ray crystal structure, 2.50 A (6FCX), catalytic-domain
     construct. No solution dynamics, no ensemble, no re-folding. A frozen-structure
     check cannot speak to any conformational change.
  2. A geometric contact is not a functional one: d_interface <= cutoff says the
     interface is structurally close, not that the position matters to assembly.
  3. Chain B is less completely modeled (41..648 vs 40..651, plus 203-204,
     220-221, 314-316), biasing d_interface slightly UPWARD there. Counted,
     not corrected.
  4. d_interface is chain-A-only by the task's definition. It is NOT a substitute
     for script 107's four-pair minimum to residue 222 — different quantity,
     different axis. The 95.13% figure has no role in this script beyond the I2-G1
     gate.
  5. Deterministic census of one structure: no resampling, no p-value, no CI,
     no null. This script tests no hypothesis. Bootstrap enters in script 127 only.
  6. This is NOT Dr. Kuhlman's second condition (conformational-change magnitude).
     Not tested here, not claimed to be tested here.
  7. BOTH cutoffs are reported always. No cutoff was chosen for giving a cleaner
     result; the 37th-residue brute stride was fixed in the docstring before the
     first run.
""")
    print(f"\nSCRIPT 126 DONE ({time.time() - t0:.1f}s)  "
          f"I2-G1 monomer {nA}/{len(fr)} = {pctA:.2f}% / dimer {nD}/{len(fr)} "
          f"= {pctD:.2f}%  |  interface-proximal 5A = {len(cls[5.0][0])}, "
          f"8A = {len(cls[8.0][0])} of {len(resolved)} resolved "
          f"({len(unresolved)} unresolved)")


if __name__ == "__main__":
    main()
